### PR TITLE
Updated to support for react16

### PR DESCRIPTION
**Pull request by hen-chow**
## STORY
With our upgrade to React16, we need to update our libraries to support React16. This update adds the use of `prop-types` library instead of using an inbuilt `React.PropTypes` property check. 

### TRELLO
https://trello.com/c/SAkX0JM8/96-react16-upgrade

### CODE REVIEW

**Comment by autopilot-pr-clerk** [comment]
#### Reviewer Checklist

- [ ] The JIRA ticket is present on this PR.
- [ ] This change is understandable or well documented.
- [ ] This PR follows the PR template.
- [ ] This PR adds or updates tests for each behaviour in this PR.

Please double check that the above are all checked or that the reasons they are not fulfiled have been justified then click the button below:

[Approve PR]( http://autopilot-pr-clerk.herokuapp.com/review/autopilothq/props-tester/4 )

**Comment by hen-chow** [comment]
[React16 Upgrade](https://trello.com/c/SAkX0JM8/96-react16-upgrade)

**Review by amandytang — APPROVED** [review]
LGTM 👍

**Review by serenezhuang — APPROVED** [review]
LGTM

**Review by exoman — APPROVED** [review]

**Pull request merged**
